### ISSUE TITLE
What Flight Tracker API can we use?

### ISSUE THREAD

**Issue by mdwiltfong** [mdwiltfong/FlightTrackerCLI#3]
There are many flight tracker APIs, but many good ones require money. What's an API that is free, and is verbose enough for us to implement in our app. 

Here are som APIs that cost money but are good:
- https://www.goflightlabs.com/
- https://serpapi.com/google-flights-api

Both cost money, but it would be great to get a free one.

**Comment by mdwiltfong** [comment]
This one has a free plan, and I think it provides some of the data we need: 
https://aviationstack.com/product

**Comment by newmanwell** [comment]
Here is one what has a free plan that seems to have all the basic info we will be using:
https://www.flightradar24.com/

**Comment by mdwiltfong** [comment]
Nice! I'll take a look. I see the API is a new feature for that site. I'm also taking a look at [OpenSky](https://openskynetwork.github.io/opensky-api/index.html)

**Comment by mdwiltfong** [comment]
I actually don't see a specific endpoint that will help us see what flights are leaving a specific airport for [flightradar24](https://fr24api.flightradar24.com/docs/endpoints)

OpenSky does have a `/flights/departure` endpoint that provides data for flights leaving a specific airport in a specific timeframe. Here's an example of Frankfurt International from January of 2018: 

```
{
        "icao24": "3c4ad0",
        "firstSeen": 1517230790,
        "estDepartureAirport": "EDDF",
        "lastSeen": 1517238306,
        "estArrivalAirport": null,
        "callsign": "DLH630  ",
        "estDepartureAirportHorizDistance": 4319,
        "estDepartureAirportVertDistance": 65,
        "estArrivalAirportHorizDistance": null,
        "estArrivalAirportVertDistance": null,
        "departureAirportCandidatesCount": 1,
        "arrivalAirportCandidatesCount": 0
    }
    ```

**Comment by DeathAdderR** [comment]
To add on the aviation stack API and considering how it's only 100 requests per month, could we cache the data for the airport/airliner codes? Then check to see if we already have data from the aviation stack API when launching the program to prevent making calls to it we don't need?

**Comment by mdwiltfong** [comment]
@DeathAdderR , that's a good idea. I think caching information would help save on API calls. Since it's a CLI App, the session is going to be short. So that means the cache wouldn't need to be reaped or cleaned up.

**Comment by mdwiltfong** [comment]
Looking at Aviationstack in greater detail I think this is a better API since it relies on API tokens versus Username and Passwords. 

I will resolve this ticket, but break it up into individual issues.
